// Supabase Database Types
// Auto-generated by Supabase CLI: npx supabase gen types typescript
// TODO: Generate from actual database schema

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      // TODO: Auto-generate table types from Supabase schema
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
